### PR TITLE
Fix network in order event

### LINKED ISSUE #435: Put the network type correctly in the events 38383 of the orders
When the events 38383 of the orders are published, they all say "network", "mainnet" in any case, even if it is another network.

It should be corrected and the event should have the real network that is being used, mainnet, regtest, or testnet or signet if it were the case, so that if a client wanted to filter by network type they could do so.

### PR DESCRIPTION
**Pull request by Catrya**
fix #435 
Now in order event 38383 the network that comes out is the correct one: mainnet, regtest, etc

## Summary by CodeRabbit

- **New Features**
	- The network tag now dynamically reflects the current network status rather than using a fixed value.

### CODE REVIEW

File: src/lightning/mod.rs [hunk 1]
```diff
@@ -271,6 +271,13 @@ impl LndConnector {
     }
 }
 
+pub async fn get_ln_status() -> Result<LnStatus, MostroError> {
```
Comment (grunch) [inline src/lightning/mod.rs:274]: we don't need this function, let's keep using LN_STATUS static

**Comment by arkanoider** [comment]
@Catrya as inspiration you could remove all modifications and just add this getter in nip33.rs:

```Rust
pub fn order_to_tags(order: &Order, reputation_data: Option<(f64, i64, i64)>) -> Tags {
    let ln_net_string = match LN_STATUS.get() {
        Some(status) => status.networks.join(","),
        None => "unknown".to_string(),
    };

    let mut tags: Vec<Tag> = vec![
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("k")),
            vec![order.kind.to_string()],
        ),
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("f")),
            vec![order.fiat_code.to_string()],
        ),
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("s")),
            vec![order.status.to_string()],
        ),
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("amt")),
            vec![order.amount.to_string()],
        ),
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("fa")),
            create_fiat_amt_array(order),
        ),
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("pm")),
            vec![order.payment_method.to_string()],
        ),
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("premium")),
            vec![order.premium.to_string()],
        ),
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("network")),
            vec![ln_net_string],
        ),
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("layer")),
            vec!["lightning".to_string()],
        ),
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("expiration")),
            vec![(order.expires_at + Duration::hours(12).num_seconds()).to_string()],
        ),
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("y")),
            vec!["mostro".to_string()],
        ),
        Tag::custom(
            TagKind::Custom(Cow::Borrowed("z")),
            vec!["order".to_string()],
        ),
    ];

    // Add reputation data if available
    if reputation_data.is_some() {
        tags.insert(
            7,
            Tag::custom(
                TagKind::Custom(Cow::Borrowed("rating")),
                vec![create_rating_tag(reputation_data)],
            ),
        );
    }

    Tags::new(tags)
}
```

So you have just one central point to touch, I let you the tests! 😄

**Comment by Catrya** [comment]
> 
> pub fn order_to_tags(order: &Order, reputation_data: Option<(f64, i64, i64)>) -> Tags {
>     let ln_net_string = match LN_STATUS.get() {
>         Some(status) => status.networks.join(","),
>         None => "unknown".to_string(),
>     };

Hi @arkanoider thanks! I just changed it a bit because lnd node can't handle multiple networks at once, so I left it to show just that one. @grunch take a look please. Thanks to both of you guys

**Comment by Catrya** [comment]
@coderabbitai review

File: src/nip33.rs [hunk 2]
```diff
@@ -77,6 +78,12 @@ fn create_fiat_amt_array(order: &Order) -> Vec<String> {
 /// * `order` - The order to transform
 ///
 pub fn order_to_tags(order: &Order, reputation_data: Option<(f64, i64, i64)>) -> Tags {
+
+    let ln_network = match LN_STATUS.get() {
+        Some(status) => status.networks.get(0).map_or("unknown".to_string(), |network| network.to_string()),
```
Comment (grunch) [inline src/nip33.rs:83]: the `networks` field is an array, we should show all elements inside, not only the first one, consider implementing the solution @arkanoider proposed

**Review by grunch — APPROVED** [review]
tACK
